# Generated by Django 5.0.2 on 2024-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
