# Generated by Django 5.0.2 on 2024-04-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_superheroe_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3)])),
                ('pregunta2', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3)])),
                ('pregunta3', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3)])),
            ],
        ),
    ]
