# Generated by Django 5.0.2 on 2024-04-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
